 ####### ember-osf settings ########
local:
  CLIENT_ID: f720c20605e84d52ad24cc97e03ed3a8
  PERSONAL_ACCESS_TOKEN: lvNe2lNnzC979B30EDPuPK6jG3MANkcThor3deBy1zaB4JQEzYfqDrF4QTPhoKUh2G6SA2
  OAUTH_SCOPES: osf.full_read osf.full_write

stage:
   CLIENT_ID: f720c20605e84d52ad24cc97e03ed3a8
   CLIENT_SECRET: F4qpuFC364JtovxTMEN9R4i9kEAq6umSrcUi1XjR
   PERSONAL_ACCESS_TOKEN: null
   OAUTH_SCOPES: osf.full_read osf.full_write

# stage2:
#   CLIENT_ID: null
#   PERSONAL_ACCESS_TOKEN: null
#   OAUTH_SCOPES: osf.full_read osf.full_write

test:
  CLIENT_ID: f720c20605e84d52ad24cc97e03ed3a8
  PERSONAL_ACCESS_TOKEN: null
  OAUTH_SCOPES: osf.full_read osf.full_write
  REDIRECT_URI: http://localhost:4200/login
  OSF_API_URL: https://test-api.osf.io/
  OSF_ACCOUNTS_URL: https://test-accounts.osf.io/
######### end ember-osf ##########
